In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[25, 16]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[27, 14], [25, 16], [28, 17], [4, 8, 24], [6, 1, 14], [25, 14], [5, 1, 17], [25, 1], [25, 14], [24, 25]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[27 14  0  0]
 [25 16  0  0]
 [28 17  0  0]
 [ 4  8 24  0]
 [ 6  1 14  0]
 [25 14  0  0]
 [ 5  1 17  0]
 [25  1  0  0]
 [25 14  0  0]
 [24 25  0  0]]


In [5]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
model.fit(X, y, epochs=50, verbose=0)

In [10]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy


1/1 [==============================] - 0s 152ms/step - loss: 0.6341 - accuracy: 1.0000


1.0

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights[13]

array([0.04533185, 0.01415007, 0.04275343, 0.03643861, 0.03915719],
      dtype=float32)

In [14]:
weights[4]

array([0.03799751, 0.10410133, 0.09243095, 0.02600237, 0.00158922],
      dtype=float32)

In [15]:
weights[16]

array([-0.04642738,  0.02759315,  0.02344233,  0.0887215 , -0.0608379 ],
      dtype=float32)

In [23]:
import numpy as np
a = np.array([1,2,3,4,5], dtype = np.int8)
b = np.array([1,2,3,4,5], dtype = np.float32)
c = np.array([1,2,3,4,5], dtype = np.int64)
p = np.array([1,2,3,4,5], dtype = np.longdouble)
q = np.array([1,2,3,4,5], dtype = np.int16)

In [24]:
print(a,b,c,p,q)

[1 2 3 4 5] [1. 2. 3. 4. 5.] [1 2 3 4 5] [1. 2. 3. 4. 5.] [1 2 3 4 5]


In [25]:
print(a.itemsize, b.itemsize, c.itemsize, p.itemsize, q.itemsize)

1 4 8 16 2


In [29]:
x=(0,8,9,15,17 ,18)
y=slice(1,-2)
x[y]

(8, 9, 15)

In [28]:
y

slice(1, -2, None)