### Word Embedding Techniques using Embedding Layer in Keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6797, 1016, 2329, 4060], [6797, 1016, 2329, 9375], [6797, 8700, 2329, 4138], [7261, 2800, 9524, 3707, 8684], [7261, 2800, 9524, 3707, 7290], [8613, 6797, 9554, 2329, 3987], [3847, 411, 6128, 3707]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6797 1016 2329 4060]
 [   0    0    0    0 6797 1016 2329 9375]
 [   0    0    0    0 6797 8700 2329 4138]
 [   0    0    0 7261 2800 9524 3707 8684]
 [   0    0    0 7261 2800 9524 3707 7290]
 [   0    0    0 8613 6797 9554 2329 3987]
 [   0    0    0    0 3847  411 6128 3707]]


In [10]:
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933
   -0.0386348  -0.00973194 -0.01386744 -0.03547372  0.02234739]
  [ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933
   -0.0386348  -0.00973194 -0.01386744 -0.03547372  0.02234739]
  [ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933
   -0.0386348  -0.00973194 -0.01386744 -0.03547372  0.02234739]
  [ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933
   -0.0386348  -0.00973194 -0.01386744 -0.03547372  0.02234739]
  [ 0.02575793 -0.03487232 -0.04677018  0.02208083  0.02429047
    0.04588285  0.03032446  0.01314508  0.00728601  0.01253195]
  [ 0.00689347  0.04103376  0.01937718 -0.01343612  0.01875408
    0.01791737 -0.00051249  0.04884868 -0.02973778 -0.021524  ]
  [-0.00020131  0.01413876 -0.00613108  0.03198499 -0.00727434
   -0.02179006 -0.02592351  0.00391436 -0.0331264   0.00231493]
  [-0.01163568  0.01829053 -0.04087238  0.00459983 -0.00508411
   -0.03286188 -0.03272481 -0.00294407  0.035822

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6797, 1016, 2329, 4060], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

[[ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933 -0.0386348
  -0.00973194 -0.01386744 -0.03547372  0.02234739]
 [ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933 -0.0386348
  -0.00973194 -0.01386744 -0.03547372  0.02234739]
 [ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933 -0.0386348
  -0.00973194 -0.01386744 -0.03547372  0.02234739]
 [ 0.00880053 -0.04343016  0.03585343  0.01540618  0.02802933 -0.0386348
  -0.00973194 -0.01386744 -0.03547372  0.02234739]
 [ 0.02575793 -0.03487232 -0.04677018  0.02208083  0.02429047  0.04588285
   0.03032446  0.01314508  0.00728601  0.01253195]
 [ 0.00689347  0.04103376  0.01937718 -0.01343612  0.01875408  0.01791737
  -0.00051249  0.04884868 -0.02973778 -0.021524  ]
 [-0.00020131  0.01413876 -0.00613108  0.03198499 -0.00727434 -0.02179006
  -0.02592351  0.00391436 -0.0331264   0.00231493]
 [-0.01163568  0.01829053 -0.04087238  0.00459983 -0.00508411 -0.03286188
  -0.03272481 -0.00294407  0.03582256  0.04907516]]
